# Generated by Django 4.1.2 on 2023-01-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cart',
        ),
    ]
