# Generated by Django 4.1.2 on 2023-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='products', verbose_name='Product Image')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ManyToManyField(to='products.imageproduct', verbose_name='Imagem do Produto'),
        ),
    ]
