# Generated by Django 4.1.2 on 2023-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_imageproduct_products_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(
                null=True, upload_to="products", verbose_name="Product Image"
            ),
        ),
    ]
