# Generated by Django 4.1.2 on 2023-02-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_category_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProduct',
        ),
    ]
