# Generated by Django 4.1.2 on 2023-02-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_imageproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Product Image'),
        ),
    ]
