# Generated by Django 4.1.2 on 2023-01-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=100, verbose_name=(('', ''), ('', ''))),
        ),
    ]
