# Generated by Django 4.1.2 on 2023-02-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="quantity",
            field=models.IntegerField(
                default=0.002471576866040534, verbose_name="Quantity"
            ),
            preserve_default=False,
        ),
    ]
