# Generated by Django 4.1.2 on 2023-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
