# Generated by Django 4.1.2 on 2023-01-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_orders_cart_product'),
        ('orders', '0003_remove_orders_client_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=100, verbose_name=(('Em andamento', 'Em andamento'), ('Cancelado', 'Cancelado'), ('Entregue', 'Entregue'))),
        ),
    ]
