# Generated by Django 4.1.2 on 2023-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orders_cart_alter_orders_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                default="Em andamento",
                max_length=100,
                verbose_name=(
                    ("Em andamento", "Em andamento"),
                    ("Cancelado", "Cancelado"),
                    ("Entregue", "Entregue"),
                ),
            ),
        ),
    ]
