# Generated by Django 4.1.2 on 2023-02-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
    ]
