# Generated by Django 4.1.2 on 2023-01-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_total_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total Sum of cart'),
        ),
    ]
