# Generated by Django 4.1.2 on 2023-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='AgroGs/media/users', verbose_name='Profile Picture'),
        ),
    ]
