# Generated by Django 4.1.2 on 2023-02-08 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Profile Picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
