# Generated by Django 4.1.2 on 2023-02-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='pic',
        ),
    ]
