# Generated by Django 4.1.2 on 2023-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_profile_pic_userprofile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Profile Picture'),
        ),
    ]
