# Generated by Django 4.1.2 on 2023-02-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_address_phone_alter_address_state_and_more"),
        ("users", "0012_alter_userprofile_pic"),
    ]

    operations = []
