# Generated by Django 4.1.2 on 2023-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20230211_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cnpj'),
        ),
    ]
